spring:
  application:
    name: nlw-unites-api
  datasource:
    url: jdbc:postgresql://localhost:5432/unite
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true